/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      black: 'hsl(var(--black))',
      white: 'hsl(var(--white))',
      blue: 'hsl(var(--blue))',
      'light-blue': 'hsl(var(--light-blue))',
      'dark-blue': 'hsl(var(--dark-blue))',
      purple: 'hsl(var(--purple))',
      'dark-purple': 'hsl(var(--dark-purple))',
      'light-purple': 'hsl(var(--light-purple))',
      teal: 'hsl(var(--teal))',
      'light-orange': 'hsl(var(--light-orange))',
      grey: 'hsl(var(--grey))',
      red: 'hsl(var(--red))',
      border: 'hsl(var(--border))',
      input: 'hsl(var(--input))',
      ring: 'hsl(var(--ring))',
      background: 'hsl(var(--background))',
      foreground: 'hsl(var(--foreground))',
      primary: {
        DEFAULT: 'hsl(var(--primary))',
        foreground: 'hsl(var(--primary-foreground))',
      },
      secondary: {
        DEFAULT: 'hsl(var(--secondary))',
        foreground: 'hsl(var(--secondary-foreground))',
      },
      muted: {
        DEFAULT: 'hsl(var(--muted))',
        foreground: 'hsl(var(--muted-foreground))',
      },
      accent: {
        DEFAULT: 'hsl(var(--accent))',
        foreground: 'hsl(var(--accent-foreground))',
      },
    },
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    fontSize: {
      h1: ['5rem', { lineHeight: '5.5rem', letterSpacing: '-0.125rem' }],
      h2: ['4rem', { lineHeight: '4.5rem', letterSpacing: '-0.125rem' }],
      h3: ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.125rem' }],
      h4: ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.125rem' }],
      h5: ['1.75rem', { lineHeight: '2.5rem', letterSpacing: '0rem' }],
      h6: ['1.125rem', { lineHeight: '1.375rem', letterSpacing: '0rem' }],
      lg: ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '0rem' }],
      base: ['1rem', { lineHeight: '1.5rem', letterSpacing: '0rem' }],
      sm: ['0.875rem', { lineHeight: '1.375rem', letterSpacing: '0rem' }],
      xs: ['0.75rem', { lineHeight: '1.25rem', letterSpacing: '0rem' }],
      btn: ['1rem', { lineHeight: '1rem', letterSpacing: '0rem' }],
    },
    extend: {
      borderRadius: {
        '3xl': '64px',
        '2xl': '56px',
        xl: '48px',
        lg: '40px',
        md: '32px',
        sm: '24px',
        xs: '16px',
        '2xs': '8px',
        '3xs': '4px',
      },
    },
  },
  plugins: [],
}
